check Debian mirrors before starting the upgrade
reason: When installing Wazo from the ISO and selecting no Debian
mirror, the machine has the Wazo repo, but no Debian mirror. The
upgrade starts correctly, but fails to upgrade any package from
Debian, eventually breaking the upgrade

diff --git a/bin/wazo-upgrade b/bin/wazo-upgrade
--- a/bin/wazo-upgrade
+++ b/bin/wazo-upgrade
@@ -5,8 +5,32 @@ PATH=/bin:/usr/bin:/sbin:/usr/sbin
 LOGFILE="/var/log/xivo-upgrade.log"
 DATEFORMAT="%Y-%m-%d_%H:%M:%S"
 
+check_package_is_available()
+{
+    local package=$1
+    test $(apt-cache madison "$package" | grep 'Packages$' | wc -l) -ge 1
+}
+
+check_debian_mirror_is_available()
+{
+    if ! check_package_is_available bash ; then
+        echo 'Could not find any Debian repository to download "bash" from. Check your /etc/apt/sources.list.'
+        return 1
+    fi
+}
+
+check_wazo_mirror_is_available()
+{
+    if ! check_package_is_available patate xivo-upgrade ; then
+        echo 'Could not find any Wazo repository to download "xivo-upgrade" from. Check your /etc/apt/sources.list.d or run "xivo-dist phoenix".'
+        return 1
+    fi
+}
+
 run_upgrade()
 {
+    check_debian_mirror_is_available || return 1
+    check_wazo_mirror_is_available || return 1
     echo "Upgrading wazo-upgrade"
     apt-get update > /dev/null
     apt-get install -y xivo-upgrade
