Check for wazo-upgrade to be installed

diff --git a/bin/wazo-upgrade b/bin/wazo-upgrade
--- a/bin/wazo-upgrade
+++ b/bin/wazo-upgrade
@@ -21,8 +21,8 @@ check_debian_mirror_is_available()
 
 check_wazo_mirror_is_available()
 {
-    if ! check_package_is_available xivo-upgrade ; then
-        echo 'Could not find any Wazo repository to download "xivo-upgrade" from. Check your /etc/apt/sources.list.d or run "xivo-dist phoenix".'
+    if ! check_package_is_available wazo-upgrade ; then
+        echo 'Could not find any Wazo repository to download "wazo-upgrade" from. Check your /etc/apt/sources.list.d or run "xivo-dist phoenix".'
         return 1
     fi
 }
